const fs=require('fs'),path=require('path'),assert=require('assert');
const read=f=>fs.readFileSync(path.resolve(__dirname,'..',f),'utf8');
const manager=read('js/modules/ticketManager.js');
const data=read('js/config/data.js');
const cart=read('js/modules/cart.js');
const payment=read('js/modules/payment.js');
const lifecycle=read('js/cloud/cloud-order-lifecycle.js');
assert(manager.includes('遊玩時間模式'));
assert(manager.includes('固定時數（1～99 小時）'));
assert(manager.includes('玩到幾點幾分'));
assert(manager.includes('ticket.playMinutes = ticket.timeMode === "duration" ? ticket.playHours * 60 : 0'));
assert(data.includes('V7.7 Ticket Rule Engine'));
assert(cart.includes('fixedExitTime'));
assert(payment.includes('playHours'));
assert(lifecycle.includes('Number(item.playHours || 0) * 60'));
console.log('PASS V7.7 ticket rule engine: 8 assertions');
