"use strict";
var assert = require("assert");
var fs = require("fs");
var path = require("path");
function read(file){ return fs.readFileSync(path.resolve(__dirname,"..",file),"utf8"); }
var manager=read("js/modules/ticketManager.js");
var catalog=read("js/modules/ticketCatalog.js");
var cart=read("js/modules/cart.js");
var validation=read("js/modules/ticketValidation.js");
var lifecycle=read("js/cloud/cloud-order-lifecycle.js");
var print=read("js/modules/print.js");
assert.ok(manager.indexOf("sortOrder")>=0,"票券管理缺少 sortOrder");
assert.ok(manager.indexOf("canEnter-")>=0,"缺少可否入場欄位");
assert.ok(manager.indexOf("pickupItemsText-")>=0,"缺少自由輸入櫃台領取欄位");
assert.ok(manager.indexOf("自由輸入")>=0,"缺少自由輸入說明");
assert.ok(catalog.indexOf("orderedTicketIds")>=0,"前台未依排序欄位顯示");
assert.ok(cart.indexOf("admissionRequired")>=0,"購物車未保存入場屬性");
assert.ok(cart.indexOf("pickupItem")>=0,"購物車未保存領取商品");
assert.ok(validation.indexOf("item.canEnter === false")>=0,"驗票未判斷可否入場");
assert.ok(lifecycle.indexOf("item.admissionRequired === false")>=0,"生命週期未判斷入場設定");
assert.ok(print.indexOf("MonsterRewardEngine.renderHtml")>=0,"完成頁未使用領取商品引擎");
console.log("PASS V7.8.2 ticket manager compatibility: 10 assertions");
