const fs=require('fs'),vm=require('vm'),assert=require('assert');
const code=fs.readFileSync('js/modules/ticketValidation.js','utf8');
const ctx={window:{},console,Date,Math,Uint8Array,crypto:{getRandomValues(a){for(let i=0;i<a.length;i++)a[i]=i+1;}}};vm.createContext(ctx);vm.runInContext(code,ctx);
const api=ctx.window.MonsterTicketValidation;
let order={orderNo:'202607180012',cloudId:'202607180012',items:[{id:'2h-green',title:'2H 綠票',price:250},{id:'token10',title:'代幣10枚',price:100}]};
api.decorateOrder(order);
assert(/^A\d{5}$/.test(order.shortCode));
assert(order.qrPayload.startsWith('MGV1:202607180012:'));
assert.equal(order.ticketInstances.length,1);
assert.equal(api.parse(order.qrPayload).orderKey,'202607180012');
console.log('ticket-validation.test.js passed');
