const fs = require('fs');
const vm = require('vm');
const assert = require('assert');
const code = fs.readFileSync('js/core/void-protection.js','utf8');
const sandbox = {window:{}, console};
vm.createContext(sandbox);
vm.runInContext(code,sandbox);
const V = sandbox.window.MonsterVoidProtection;
assert(V);
assert.strictEqual(V.isVoided({status:'cancel'}), true);
assert.strictEqual(V.isVoided({playStatus:'cancelled'}), true);
assert.strictEqual(V.isVoided({status:'voided'}), true);
assert.strictEqual(V.isVoided({cancelled:true}), true);
assert.strictEqual(V.isVoided({status:'paid',playStatus:'waiting'}), false);
const stamp = V.stamp('測試',{name:'店長',id:'m1',role:'admin'});
assert.strictEqual(stamp.status,'cancel');
assert.strictEqual(stamp.playStatus,'cancelled');
assert.strictEqual(stamp.validationStatus,'cancelled');
assert.strictEqual(stamp.cancelled,true);
assert.strictEqual(stamp.voided,true);
console.log('V7.8.3 void protection tests passed');
