const fs = require('fs');
const vm = require('vm');
const assert = require('assert');
const code = fs.readFileSync('js/core/ticket-status-engine.js','utf8');
const context = { window: {} };
vm.createContext(context);
vm.runInContext(code, context);
const engine = context.window.MonsterTicketStatusEngine;
assert(engine, 'engine should exist');
assert.equal(engine.getOrderStatus({playStatus:'playing'}), 'playing');
assert.equal(engine.getOrderStatus({playStatus:'playing',ticketInstances:[{status:'finished'}]}), 'finished');
assert.equal(engine.getOrderStatus({ticketInstances:[{status:'playing'},{status:'finished'}]}), 'playing');
const exited = engine.transitionOrder({playStatus:'playing',ticketInstances:[{status:'playing'}]}, 'finished', {now:1000,actor:'staff'});
assert.equal(exited.playStatus, 'finished');
assert.equal(exited.validationStatus, 'finished');
assert.equal(exited.ticketInstances[0].status, 'finished');
assert.equal(exited.ticketInstances[0].checkedOutAt, 1000);
console.log('ticket-status-engine.test.js passed');
